site_name: WorldEdit for Minecraft Bedrock
repo_url: https://github.com/SIsilicon/WorldEdit-BE-Docs

markdown_extensions:
  - admonition
  - tables
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

theme:
  name: readthedocs
  locale: en

extra_css: [css/extra.css]

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quick_start.md
  - Configuration: configuration.md
  - Commands: commands.md
  - Differences: differences.md
  - FAQ: common_questions.md
  - Usage:
    - General:
      - History: usage/general/history.md
      - Sessions: usage/general/sessions.md
      - Patterns: usage/general/patterns.md
      - Masks: usage/general/masks.md
    - Regions:
      - Region Operations: usage/regions/region_operations.md
      - Selection: usage/regions/selection.md
    - Kit: usage/kit.md
    - Navigation: usage/navigation.md
    - Clipboard: usage/clipboard.md
    - Generation: usage/generation.md
    - Tools: usage/tools.md
    - Brushes: usage/brushes.md

python:
  install:
    - requirements: docs/requirements.txt